#ifndef __myframe__
#define __myframe__

/**
@file
Subclass of MyFrameBase, which is generated by wxFormBuilder.
*/

#include "gui.h"

//// end generated include

/** Implementing MyFrameBase */
class MyFrame : public MyFrameBase
{
	public:
		/** Constructor */
		MyFrame( wxWindow* parent );
	//// end generated class members
	
};

#endif // __myframe__
